create delete tests for api + ssr tests for apis page
Nebo15/gateway.web pull request #22
Opened 2017-01-20 12:16 UTC by furmanjmx

2017-01-23 19:50 UTC, alexeybondarenko requested changes

2017-01-23 19:50 UTC, alexeybondarenko commented on app/common/containers/pages/ApiListPage/index.js
> +              action: (<Button id="edit-api-button" theme="link" to={`apis/${i.id}`}>Edit&nbsp;API</Button>),
так нельзя. этих кнопок будет много. а id на странице должны быть уникальными

2017-01-24 12:11 UTC, alexeybondarenko requested changes

2017-01-24 12:11 UTC, alexeybondarenko commented on app/common/containers/pages/ApiEditPage/index.js
> +                <Button id="edit-plugin-button" theme="link" to={`/apis/${item.api_id}/plugins/${item.id}`}>
у тебя будет несколько одинаковых id-шников. такое нельзя делать

2017-01-24 13:28 UTC, furmanjmx commented on app/common/containers/pages/ApiEditPage/index.js
> +                <Button id="edit-plugin-button" theme="link" to={`/apis/${item.api_id}/plugins/${item.id}`}>
пофиксил

2017-01-26 12:42 UTC, alexeybondarenko approved these changes

2017-01-26 12:42 UTC, merged